name: Deploy Documentation
on:
  push:
    branches:
      - "*"
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup Document Dependencies
        run: |
          pip install -r ./docs/requirements.txt

      - name: Build with MKDocs
        run: |
          mkdocs build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_PAGES_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: graia-broadcast
          directory: site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
